"""Public bindings used to model supported Invoke star imports."""

__all__ = ["STAR_EXPORTS"]

# Public bindings of the supported Invoke modules. Star imports replace these
# names, while unrelated project functions and aliases remain bound.
STAR_EXPORTS = {
    "invoke": frozenset([
        "metadata",
        "Any",
        "Collection",
        "Config",
        "Context",
        "MockContext",
        "AmbiguousEnvVar",
        "AuthFailure",
        "CollectionNotFound",
        "CommandTimedOut",
        "Exit",
        "ParseError",
        "PlatformError",
        "ResponseNotAccepted",
        "SubprocessPipeError",
        "ThreadException",
        "UncastableEnvVar",
        "UnexpectedExit",
        "UnknownFileType",
        "UnpicklableConfigMember",
        "WatcherError",
        "Executor",
        "FilesystemLoader",
        "Argument",
        "Parser",
        "ParserContext",
        "ParseResult",
        "Program",
        "Failure",
        "Local",
        "Promise",
        "Result",
        "Runner",
        "Call",
        "Task",
        "call",
        "task",
        "pty_size",
        "FailingResponder",
        "Responder",
        "StreamWatcher",
        "run",
        "sudo",
        "collection",
        "config",
        "context",
        "exceptions",
        "executor",
        "loader",
        "parser",
        "program",
        "runners",
        "tasks",
        "terminals",
        "watchers",
        "util",
        "env",
        "completion",
        "vendor",
    ]),
    "invoke.tasks": frozenset([
        "inspect",
        "types",
        "deepcopy",
        "update_wrapper",
        "TYPE_CHECKING",
        "Any",
        "Callable",
        "Dict",
        "Generic",
        "Iterable",
        "List",
        "Optional",
        "Set",
        "Tuple",
        "Type",
        "TypeVar",
        "Union",
        "Context",
        "Argument",
        "ParseResult",
        "translate_underscores",
        "T",
        "Task",
        "task",
        "Call",
        "call",
    ]),
}
